<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\bin\Release\BoxKite.Twitter.Tests.DLL" configFile="C:\Dropbox\OSS\nickhodge\BoxKite.Twitter\tools\xunit.runner.console\tools\xunit.console.exe.Config" run-date="2017-07-09" run-time="19:17:42" time="2.332" total="125" passed="87" failed="38" skipped="0" environment="64-bit .NET 4.0.30319.42000 [collection-per-class, parallel (2 threads)]" test-framework="xUnit.net 2.2.0.3545">
    <class name="BoxKite.Twitter.Tests.AdditionalTweetAndTimelineTests" time="0.710" total="3" passed="3" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.AdditionalTweetAndTimelineTests.Parse_Tweet_with_encodings" type="BoxKite.Twitter.Tests.AdditionalTweetAndTimelineTests" method="Parse_Tweet_with_encodings" result="Pass" time="0.0033808" />
      <test name="BoxKite.Twitter.Tests.AdditionalTweetAndTimelineTests.Parse_Tweet_with_encodings_part_deux" type="BoxKite.Twitter.Tests.AdditionalTweetAndTimelineTests" method="Parse_Tweet_with_encodings_part_deux" result="Pass" time="0.6154996" />
      <test name="BoxKite.Twitter.Tests.AdditionalTweetAndTimelineTests.Parse_Twitter_timeline_with_over_200_tweets" type="BoxKite.Twitter.Tests.AdditionalTweetAndTimelineTests" method="Parse_Twitter_timeline_with_over_200_tweets" result="Pass" time="0.0914866" />
    </class>
    <class name="BoxKite.Twitter.Tests.ApiManagemenentExtensionsTests" time="0.913" total="1" passed="1" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.ApiManagemenentExtensionsTests.Get_Twitter_API_Limits" type="BoxKite.Twitter.Tests.ApiManagemenentExtensionsTests" method="Get_Twitter_API_Limits" result="Pass" time="0.9133445" />
    </class>
    <class name="BoxKite.Twitter.Tests.ApiManagemenentExtensionsTestsAppAuth" time="1.033" total="1" passed="1" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.ApiManagemenentExtensionsTestsAppAuth.Get_Twitter_API_Limits_AppAuth" type="BoxKite.Twitter.Tests.ApiManagemenentExtensionsTestsAppAuth" method="Get_Twitter_API_Limits_AppAuth" result="Pass" time="1.0329212" />
    </class>
    <class name="BoxKite.Twitter.Tests.DecodeTests" time="0.685" total="7" passed="5" failed="2" skipped="0">
      <test name="BoxKite.Twitter.Tests.DecodeTests.Decode_Deep_ReTweet" type="BoxKite.Twitter.Tests.DecodeTests" method="Decode_Deep_ReTweet" result="Pass" time="0.0008869" />
      <test name="BoxKite.Twitter.Tests.DecodeTests.Decode_Entity_HashTag_Separate_Tests" type="BoxKite.Twitter.Tests.DecodeTests" method="Decode_Entity_HashTag_Separate_Tests" result="Pass" time="0.0027957" />
      <test name="BoxKite.Twitter.Tests.DecodeTests.Decode_Entity_Media_Separate_Tests" type="BoxKite.Twitter.Tests.DecodeTests" method="Decode_Entity_Media_Separate_Tests" result="Pass" time="0.0165441" />
      <test name="BoxKite.Twitter.Tests.DecodeTests.Decode_Entity_Mentions_Separate_Tests" type="BoxKite.Twitter.Tests.DecodeTests" method="Decode_Entity_Mentions_Separate_Tests" result="Pass" time="0.458935" />
      <test name="BoxKite.Twitter.Tests.DecodeTests.Decode_Entity_Urls_Separate_Tests" type="BoxKite.Twitter.Tests.DecodeTests" method="Decode_Entity_Urls_Separate_Tests" result="Pass" time="0.0040208" />
      <test name="BoxKite.Twitter.Tests.DecodeTests.Decode_Tweet_Deep_Tests" type="BoxKite.Twitter.Tests.DecodeTests" method="Decode_Tweet_Deep_Tests" result="Fail" time="0.0995706">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected a value.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Numeric.NullableNumericAssertions`1.HaveValue(String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NullableNumericAssertions.cs:line 25
   at FluentAssertions.Numeric.NullableNumericAssertions`1.NotBeNull(String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Numeric\NullableNumericAssertions.cs:line 45
   at BoxKite.Twitter.Tests.DecodeTests.Decode_Tweet_Deep_Tests() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\DecodeTests.cs:line 152</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.DecodeTests.Decode_User_Deep_Tests" type="BoxKite.Twitter.Tests.DecodeTests" method="Decode_User_Deep_Tests" result="Fail" time="0.1021796">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string not to be &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.NotBeNull(String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\ReferenceTypeAssertions.cs:line 53
   at BoxKite.Twitter.Tests.DecodeTests.Decode_User_Deep_Tests() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\DecodeTests.cs:line 215</stack-trace>
        </failure>
      </test>
    </class>
    <class name="BoxKite.Twitter.Tests.DirectMessagesTests" time="1.355" total="5" passed="3" failed="2" skipped="0">
      <test name="BoxKite.Twitter.Tests.DirectMessagesTests.Create_and_Send_DirectMessage" type="BoxKite.Twitter.Tests.DirectMessagesTests" method="Create_and_Send_DirectMessage" result="Fail" time="1.0147532">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/direct_messages/new.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.DirectMessageExtensions.&lt;SendDirectMessage&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.DirectMessagesTests.&lt;Create_and_Send_DirectMessage&gt;d__4.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\DirectMessagesTests.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.DirectMessagesTests.Delete_Sent_DirectMessage" type="BoxKite.Twitter.Tests.DirectMessagesTests" method="Delete_Sent_DirectMessage" result="Fail" time="0.063883">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/direct_messages/destroy.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.DirectMessageExtensions.&lt;DeleteDirectMessage&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.DirectMessagesTests.&lt;Delete_Sent_DirectMessage&gt;d__5.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\DirectMessagesTests.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.DirectMessagesTests.Get_DirectMessages_received" type="BoxKite.Twitter.Tests.DirectMessagesTests" method="Get_DirectMessages_received" result="Pass" time="0.0695664" />
      <test name="BoxKite.Twitter.Tests.DirectMessagesTests.Get_DirectMessages_sent" type="BoxKite.Twitter.Tests.DirectMessagesTests" method="Get_DirectMessages_sent" result="Pass" time="0.1348912" />
      <test name="BoxKite.Twitter.Tests.DirectMessagesTests.Get_Single_DirectMessage" type="BoxKite.Twitter.Tests.DirectMessagesTests" method="Get_Single_DirectMessage" result="Pass" time="0.0717356" />
    </class>
    <class name="BoxKite.Twitter.Tests.ErrorTests" time="0.594" total="4" passed="4" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.ErrorTests.Get_DirectMessages_Parameter_EnsureAll_Error" type="BoxKite.Twitter.Tests.ErrorTests" method="Get_DirectMessages_Parameter_EnsureAll_Error" result="Pass" time="0.0618823" />
      <test name="BoxKite.Twitter.Tests.ErrorTests.Get_Lists_Parameter_EitherOr_Error" type="BoxKite.Twitter.Tests.ErrorTests" method="Get_Lists_Parameter_EitherOr_Error" result="Pass" time="0.345031" />
      <test name="BoxKite.Twitter.Tests.ErrorTests.Get_Rate_LimitExceeded_Error_OnCollection" type="BoxKite.Twitter.Tests.ErrorTests" method="Get_Rate_LimitExceeded_Error_OnCollection" result="Pass" time="0.070598" />
      <test name="BoxKite.Twitter.Tests.ErrorTests.Get_Rate_LimitExceeded_Error_OnSingle" type="BoxKite.Twitter.Tests.ErrorTests" method="Get_Rate_LimitExceeded_Error_OnSingle" result="Pass" time="0.1168955" />
    </class>
    <class name="BoxKite.Twitter.Tests.FavouritesTests" time="1.171" total="3" passed="1" failed="2" skipped="0">
      <test name="BoxKite.Twitter.Tests.FavouritesTests.Create_Favourite_For_CurrentUser_ReturnsResult" type="BoxKite.Twitter.Tests.FavouritesTests" method="Create_Favourite_For_CurrentUser_ReturnsResult" result="Fail" time="0.0713934">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/favorites/create.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.FavouritesExtensions.&lt;CreateFavourite&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.FavouritesTests.&lt;Create_Favourite_For_CurrentUser_ReturnsResult&gt;d__2.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\FavouritesTests.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.FavouritesTests.Delete_Favourite_For_CurrentUser_ReturnsResult" type="BoxKite.Twitter.Tests.FavouritesTests" method="Delete_Favourite_For_CurrentUser_ReturnsResult" result="Fail" time="0.9904143">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/favorites/destroy.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.FavouritesExtensions.&lt;DeleteFavourite&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.FavouritesTests.&lt;Delete_Favourite_For_CurrentUser_ReturnsResult&gt;d__3.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\FavouritesTests.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.FavouritesTests.Get_Favourites_For_CurrentUser_ReturnsSet" type="BoxKite.Twitter.Tests.FavouritesTests" method="Get_Favourites_For_CurrentUser_ReturnsSet" result="Pass" time="0.1093772" />
    </class>
    <class name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" time="0.886" total="11" passed="9" failed="2" skipped="0">
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Change_Friendship" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Change_Friendship" result="Fail" time="0.0872987">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/friendships/update.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.FriendsFollowersExtensions.&lt;ChangeFriendship&gt;d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.&lt;Change_Friendship&gt;d__8.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\FriendsFollowersExtensionsTests.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Create_Friendship" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Create_Friendship" result="Pass" time="0.0935961" />
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Delete_Friendship" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Delete_Friendship" result="Pass" time="0.0243243" />
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Get_Followers_IDs" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Get_Followers_IDs" result="Pass" time="0.0378784" />
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Get_Followers_List_Detailed_Cursored" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Get_Followers_List_Detailed_Cursored" result="Pass" time="0.0620537" />
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Get_Friends_IDs" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Get_Friends_IDs" result="Pass" time="0.0277562" />
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Get_Friends_List_Detailed_Cursored" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Get_Friends_List_Detailed_Cursored" result="Pass" time="0.0257518" />
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Get_Friendship" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Get_Friendship" result="Fail" time="0.0099981">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/friendships/show.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.FriendsFollowersExtensions.&lt;GetFriendship&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.&lt;Get_Friendship&gt;d__9.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\FriendsFollowersExtensionsTests.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Get_Friendship_Status_lookup" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Get_Friendship_Status_lookup" result="Pass" time="0.3392474" />
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Get_Incoming_Friend_Requests" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Get_Incoming_Friend_Requests" result="Pass" time="0.050082" />
      <test name="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests.Get_Outgoing_Friend_Requests" type="BoxKite.Twitter.Tests.FriendsFollowersExtensionsTests" method="Get_Outgoing_Friend_Requests" result="Pass" time="0.1284998" />
    </class>
    <class name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" time="1.594" total="19" passed="10" failed="9" skipped="0">
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Change_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Change_List" result="Fail" time="0.0908679">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/lists/update.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ListExtensions.&lt;ChangeList&gt;d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.Modules.ListExtensionsTests.&lt;Change_List&gt;d__8.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ListExtensionsTests.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Create_A_Subscribe_To_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Create_A_Subscribe_To_List" result="Fail" time="0.0136803">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/lists/subscribers/create.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ListExtensions.&lt;SubscribeToUsersList&gt;d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.Modules.ListExtensionsTests.&lt;Create_A_Subscribe_To_List&gt;d__11.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ListExtensionsTests.cs:line 171
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Create_A_User_In_My_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Create_A_User_In_My_List" result="Fail" time="0.0121818">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/lists/members/create.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ListExtensions.&lt;AddUserToMyList&gt;d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.Modules.ListExtensionsTests.&lt;Create_A_User_In_My_List&gt;d__7.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ListExtensionsTests.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Create_New_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Create_New_List" result="Fail" time="0.0158929">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/lists/create.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ListExtensions.&lt;CreateList&gt;d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.Modules.ListExtensionsTests.&lt;Create_New_List&gt;d__12.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ListExtensionsTests.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Create_User_Entry_In_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Create_User_Entry_In_List" result="Fail" time="0.0427614">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/lists/members/create_all.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ListExtensions.&lt;AddUsersToList&gt;d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.Modules.ListExtensionsTests.&lt;Create_User_Entry_In_List&gt;d__5.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ListExtensionsTests.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Delete_From_Users_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Delete_From_Users_List" result="Fail" time="0.0182">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/lists/subscribers/destroy.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ListExtensions.&lt;DeleteFromUsersList&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.Modules.ListExtensionsTests.&lt;Delete_From_Users_List&gt;d__4.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ListExtensionsTests.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Delete_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Delete_List" result="Fail" time="0.0103971">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/lists/destroy.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ListExtensions.&lt;DeleteList&gt;d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.Modules.ListExtensionsTests.&lt;Delete_List&gt;d__19.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ListExtensionsTests.cs:line 287
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Delete_User_From_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Delete_User_From_List" result="Fail" time="0.0513683">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/lists/members/destroy\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ListExtensions.&lt;DeleteUserFromList&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.Modules.ListExtensionsTests.&lt;Delete_User_From_List&gt;d__3.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ListExtensionsTests.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Delete_Users_From_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Delete_Users_From_List" result="Fail" time="0.0147838">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/lists/members/destroy_all.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ListExtensions.&lt;DeleteUsersFromList&gt;d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.Modules.ListExtensionsTests.&lt;Delete_Users_From_List&gt;d__6.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ListExtensionsTests.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_Is_Subscribed_To_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_Is_Subscribed_To_List" result="Pass" time="0.0097047" />
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_Is_User_On_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_Is_User_On_List" result="Pass" time="0.028442" />
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_List_Subscribers" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_List_Subscribers" result="Pass" time="0.0430252" />
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_List_Timeline" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_List_Timeline" result="Pass" time="0.0547271" />
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_Lists" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_Lists" result="Pass" time="0.0338845" />
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_Lists_Owned" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_Lists_Owned" result="Pass" time="0.0272405" />
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_Members_On_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_Members_On_List" result="Pass" time="0.0298546" />
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_Single_List" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_Single_List" result="Pass" time="0.0625768" />
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_Subscriptions_Cursored" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_Subscriptions_Cursored" result="Pass" time="0.0642932" />
      <test name="BoxKite.Twitter.Tests.Modules.ListExtensionsTests.Get_User_Membership" type="BoxKite.Twitter.Tests.Modules.ListExtensionsTests" method="Get_User_Membership" result="Pass" time="0.9702761" />
    </class>
    <class name="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests" time="1.327" total="5" passed="4" failed="1" skipped="0">
      <test name="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests.Create_Place" type="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests" method="Create_Place" result="Fail" time="0.0620113">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/geo/create.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.PlacesGeoExtensions.&lt;CreatePlace&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.PlaceGeoExtensionsTests.&lt;Create_Place&gt;d__5.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\PlaceGeoExtensionsTests.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests.Get_Place_Info" type="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests" method="Get_Place_Info" result="Pass" time="0.1353682" />
      <test name="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests.Get_Places_for_Tweetage" type="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests" method="Get_Places_for_Tweetage" result="Pass" time="0.0613477" />
      <test name="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests.Get_Places_From_Current_Location" type="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests" method="Get_Places_From_Current_Location" result="Pass" time="0.067164" />
      <test name="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests.Get_Similar_Places" type="BoxKite.Twitter.Tests.PlaceGeoExtensionsTests" method="Get_Similar_Places" result="Pass" time="1.0007757" />
    </class>
    <class name="BoxKite.Twitter.Tests.ReportExtensionsTest" time="0.903" total="1" passed="0" failed="1" skipped="0">
      <test name="BoxKite.Twitter.Tests.ReportExtensionsTest.Get_Trends_For_Place" type="BoxKite.Twitter.Tests.ReportExtensionsTest" method="Get_Trends_For_Place" result="Fail" time="0.9028585">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/users/report_spam.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.ReportExtensions.&lt;ReportUserForSpam&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.ReportExtensionsTest.&lt;Get_Trends_For_Place&gt;d__1.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\ReportExtensionsTests.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
    </class>
    <class name="BoxKite.Twitter.Tests.SearchExtensionsTests" time="0.621" total="6" passed="3" failed="3" skipped="0">
      <test name="BoxKite.Twitter.Tests.SearchExtensionsTests.Create_Save_A_Saved_Search_by_Saving" type="BoxKite.Twitter.Tests.SearchExtensionsTests" method="Create_Save_A_Saved_Search_by_Saving" result="Fail" time="0.0559275">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/saved_searches/create.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.SearchExtensions.&lt;CreateSaveSearch&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.SearchExtensionsTests.&lt;Create_Save_A_Saved_Search_by_Saving&gt;d__6.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\SearchExtensionsTests.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.SearchExtensionsTests.Delete_A_Saved_Search" type="BoxKite.Twitter.Tests.SearchExtensionsTests" method="Delete_A_Saved_Search" result="Fail" time="0.0319816">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/saved_searches/destroy/62353170.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.SearchExtensions.&lt;DeleteSavedSearch&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.SearchExtensionsTests.&lt;Delete_A_Saved_Search&gt;d__5.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\SearchExtensionsTests.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.SearchExtensionsTests.Get_A_Saved_Search" type="BoxKite.Twitter.Tests.SearchExtensionsTests" method="Get_A_Saved_Search" result="Pass" time="0.097891" />
      <test name="BoxKite.Twitter.Tests.SearchExtensionsTests.Get_Saved_Search_Queries" type="BoxKite.Twitter.Tests.SearchExtensionsTests" method="Get_Saved_Search_Queries" result="Fail" time="0.3341621">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected subject to be \r\n\"15/06/2010 9:38:04 AM +00:00\" with a length of 28, but \r\n\"6/15/2010 9:38:04 AM +00:00\" has a length of 27.\r\n\nWith configuration:\n- Use declared types and members\r\n- Compare enums by value\r\n- Match member by name (or throw)\r\n- Be strict about the order of items in byte arrays\r\n</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\CollectingAssertionStrategy.cs:line 50
   at FluentAssertions.Execution.AssertionScope.Dispose() in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 252
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\Core\Equivalency\EquivalencyValidator.cs:line 41
   at FluentAssertions.AssertionExtensions.ShouldBeEquivalentTo[T](T subject, Object expectation, Func`2 config, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Shared\AssertionExtensions.cs:line 745
   at FluentAssertions.AssertionExtensions.ShouldBeEquivalentTo[T](T subject, Object expectation, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Shared\AssertionExtensions.cs:line 704
   at BoxKite.Twitter.Tests.SearchExtensionsTests.&lt;Get_Saved_Search_Queries&gt;d__3.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\SearchExtensionsTests.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.SearchExtensionsTests.Search_Query_Geocoded" type="BoxKite.Twitter.Tests.SearchExtensionsTests" method="Search_Query_Geocoded" result="Pass" time="0.0254848" />
      <test name="BoxKite.Twitter.Tests.SearchExtensionsTests.Search_Query_received" type="BoxKite.Twitter.Tests.SearchExtensionsTests" method="Search_Query_received" result="Pass" time="0.0755493" />
    </class>
    <class name="BoxKite.Twitter.Tests.SearchStreamTests" time="1.044" total="1" passed="1" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.SearchStreamTests.SearchStream1_incoming_Tweets" type="BoxKite.Twitter.Tests.SearchStreamTests" method="SearchStream1_incoming_Tweets" result="Pass" time="1.0437542" />
    </class>
    <class name="BoxKite.Twitter.Tests.SuggestedUsersExtensionsTests" time="1.458" total="2" passed="2" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.SuggestedUsersExtensionsTests.Get_Suggested_User_Lists_as_Slugs" type="BoxKite.Twitter.Tests.SuggestedUsersExtensionsTests" method="Get_Suggested_User_Lists_as_Slugs" result="Pass" time="0.1060119" />
      <test name="BoxKite.Twitter.Tests.SuggestedUsersExtensionsTests.Get_Suggested_Users_foraSlug" type="BoxKite.Twitter.Tests.SuggestedUsersExtensionsTests" method="Get_Suggested_Users_foraSlug" result="Pass" time="1.3519474" />
    </class>
    <class name="BoxKite.Twitter.Tests.TimelineExtensionsTests" time="1.349" total="5" passed="5" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.TimelineExtensionsTests.Get_Mentions_Timeline" type="BoxKite.Twitter.Tests.TimelineExtensionsTests" method="Get_Mentions_Timeline" result="Pass" time="0.0533656" />
      <test name="BoxKite.Twitter.Tests.TimelineExtensionsTests.Get_Retweets_Of_Me" type="BoxKite.Twitter.Tests.TimelineExtensionsTests" method="Get_Retweets_Of_Me" result="Pass" time="0.1146527" />
      <test name="BoxKite.Twitter.Tests.TimelineExtensionsTests.Get_User_Homeline" type="BoxKite.Twitter.Tests.TimelineExtensionsTests" method="Get_User_Homeline" result="Pass" time="0.0750619" />
      <test name="BoxKite.Twitter.Tests.TimelineExtensionsTests.Get_User_Timeline" type="BoxKite.Twitter.Tests.TimelineExtensionsTests" method="Get_User_Timeline" result="Pass" time="1.0333313" />
      <test name="BoxKite.Twitter.Tests.TimelineExtensionsTests.Get_User_Timeline_with_name" type="BoxKite.Twitter.Tests.TimelineExtensionsTests" method="Get_User_Timeline_with_name" result="Pass" time="0.0728896" />
    </class>
    <class name="BoxKite.Twitter.Tests.TimelineExtensionsTestsAppAuth" time="1.042" total="1" passed="1" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.TimelineExtensionsTestsAppAuth.Get_User_Timeline_AppAuth" type="BoxKite.Twitter.Tests.TimelineExtensionsTestsAppAuth" method="Get_User_Timeline_AppAuth" result="Pass" time="1.0421774" />
    </class>
    <class name="BoxKite.Twitter.Tests.TrendsExtensionsTests" time="1.141" total="3" passed="3" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.TrendsExtensionsTests.Get_Trend_Locations_Available" type="BoxKite.Twitter.Tests.TrendsExtensionsTests" method="Get_Trend_Locations_Available" result="Pass" time="0.9387894" />
      <test name="BoxKite.Twitter.Tests.TrendsExtensionsTests.Get_Trends_By_LatLong" type="BoxKite.Twitter.Tests.TrendsExtensionsTests" method="Get_Trends_By_LatLong" result="Pass" time="0.1082444" />
      <test name="BoxKite.Twitter.Tests.TrendsExtensionsTests.Get_Trends_For_Place" type="BoxKite.Twitter.Tests.TrendsExtensionsTests" method="Get_Trends_For_Place" result="Pass" time="0.0935149" />
    </class>
    <class name="BoxKite.Twitter.Tests.TweetExtensionsTests" time="1.401" total="10" passed="3" failed="7" skipped="0">
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Create_And_Send_Tweet" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Create_And_Send_Tweet" result="Fail" time="0.0333313">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/statuses/update.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.TweetExtensions.&lt;SendTweet&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.TweetExtensionsTests.&lt;Create_And_Send_Tweet&gt;d__1.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\TweetExtensionsTests.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Create_And_Send_Tweet_With_Image" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Create_And_Send_Tweet_With_Image" result="Fail" time="1.0090835">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/statuses/update_with_media.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostFileAsync(String url, SortedDictionary`2 parameters, String fileName, String fileContentsKey, Byte[] fileContents, Stream srReader) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 103
   at BoxKite.Twitter.TweetExtensions.&lt;SendTweetWithImage&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.TweetExtensionsTests.&lt;Create_And_Send_Tweet_With_Image&gt;d__9.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\TweetExtensionsTests.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Create_And_Send_Tweet_with_location" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Create_And_Send_Tweet_with_location" result="Fail" time="0.0089775">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/statuses/update.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.TweetExtensions.&lt;SendTweet&gt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.TweetExtensionsTests.&lt;Create_And_Send_Tweet_with_location&gt;d__2.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\TweetExtensionsTests.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Create_Reply_To_Tweet" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Create_Reply_To_Tweet" result="Fail" time="0.0564788">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/statuses/update.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.TweetExtensions.&lt;ReplyToTweet&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.TweetExtensionsTests.&lt;Create_Reply_To_Tweet&gt;d__4.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\TweetExtensionsTests.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Create_Reply_To_Tweet_with_Location" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Create_Reply_To_Tweet_with_Location" result="Fail" time="0.0112794">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/statuses/update.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.TweetExtensions.&lt;ReplyToTweet&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.TweetExtensionsTests.&lt;Create_Reply_To_Tweet_with_Location&gt;d__5.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\TweetExtensionsTests.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Create_ReTweet" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Create_ReTweet" result="Fail" time="0.0613252">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/statuses/retweet/243149503589400576.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.TweetExtensions.&lt;Retweet&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.TweetExtensionsTests.&lt;Create_ReTweet&gt;d__6.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\TweetExtensionsTests.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Delete_Tweet" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Delete_Tweet" result="Fail" time="0.01124">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/statuses/destroy/243145735212777472.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.TweetExtensions.&lt;DeleteTweet&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.TweetExtensionsTests.&lt;Delete_Tweet&gt;d__3.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\TweetExtensionsTests.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Get_Retweets_Of_Tweet" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Get_Retweets_Of_Tweet" result="Pass" time="0.0346103" />
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Get_Tweet" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Get_Tweet" result="Pass" time="0.0681314" />
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTests.Get_Tweet_with_Extended_Entities" type="BoxKite.Twitter.Tests.TweetExtensionsTests" method="Get_Tweet_with_Extended_Entities" result="Pass" time="0.1068213" />
    </class>
    <class name="BoxKite.Twitter.Tests.TweetExtensionsTestsAppAuth" time="1.432" total="1" passed="1" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.TweetExtensionsTestsAppAuth.Get_Retweets_Of_Tweet_AppAuth" type="BoxKite.Twitter.Tests.TweetExtensionsTestsAppAuth" method="Get_Retweets_Of_Tweet_AppAuth" result="Pass" time="1.4321279" />
    </class>
    <class name="BoxKite.Twitter.Tests.UsersExtensionsTests" time="1.692" total="19" passed="10" failed="9" skipped="0">
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Change_Account_Colours" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Change_Account_Colours" result="Fail" time="0.016722">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/account/update_profile_colors.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.UsersExtensions.&lt;ChangeAccountColours&gt;d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.UsersExtensionsTests.&lt;Change_Account_Colours&gt;d__13.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\UsersExtensionsTests.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Change_Account_Profile" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Change_Account_Profile" result="Fail" time="0.026253">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/account/update_profile.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.UsersExtensions.&lt;ChangeAccountProfile&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.UsersExtensionsTests.&lt;Change_Account_Profile&gt;d__3.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\UsersExtensionsTests.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Change_Account_Profile_Colours" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Change_Account_Profile_Colours" result="Fail" time="0.0033292">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/account/update_profile_colors.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.UsersExtensions.&lt;ChangeAccountColours&gt;d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.UsersExtensionsTests.&lt;Change_Account_Profile_Colours&gt;d__4.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\UsersExtensionsTests.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Change_Account_Settings" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Change_Account_Settings" result="Fail" time="0.9995047">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/account/settings.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.UsersExtensions.&lt;ChangeAccountSettings&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.UsersExtensionsTests.&lt;Change_Account_Settings&gt;d__2.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\UsersExtensionsTests.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Change_BackgroundImage" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Change_BackgroundImage" result="Fail" time="0.0986863">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/account/update_profile_background_image.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostFileAsync(String url, SortedDictionary`2 parameters, String fileName, String fileContentsKey, Byte[] fileContents, Stream srReader) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 103
   at BoxKite.Twitter.UsersExtensions.&lt;ChangeAccountBackgroundImage&gt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.UsersExtensionsTests.&lt;Change_BackgroundImage&gt;d__11.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\UsersExtensionsTests.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Change_Profile_Image" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Change_Profile_Image" result="Fail" time="0.0046708">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/account/update_profile_image.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostFileAsync(String url, SortedDictionary`2 parameters, String fileName, String fileContentsKey, Byte[] fileContents, Stream srReader) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 103
   at BoxKite.Twitter.UsersExtensions.&lt;ChangeAccountProfileImage&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.UsersExtensionsTests.&lt;Change_Profile_Image&gt;d__10.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\UsersExtensionsTests.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Create_Block_on_User" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Create_Block_on_User" result="Fail" time="0.0053737">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/blocks/create.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.UsersExtensions.&lt;CreateUserBlock&gt;d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.UsersExtensionsTests.&lt;Create_Block_on_User&gt;d__15.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\UsersExtensionsTests.cs:line 211
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Delete_Block_on_User" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Delete_Block_on_User" result="Fail" time="0.0164527">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/blocks/destroy.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.UsersExtensions.&lt;DeleteUserBlock&gt;d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.UsersExtensionsTests.&lt;Delete_Block_on_User&gt;d__16.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\UsersExtensionsTests.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_Account_Settings" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_Account_Settings" result="Pass" time="0.0405498" />
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_Banner" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_Banner" result="Pass" time="0.1184971" />
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_BlockList_cursored" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_BlockList_cursored" result="Pass" time="0.055336" />
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_Configuration" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_Configuration" result="Pass" time="0.0751343" />
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_Profile_WhenIdSent_ParsesResult" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_Profile_WhenIdSent_ParsesResult" result="Pass" time="0.0129043" />
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_Profile_WhenIdSent_ReceivesNameAsParameter" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_Profile_WhenIdSent_ReceivesNameAsParameter" result="Pass" time="0.0198104" />
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_Profile_WhenUserSent_ReceivesNameAsParameter" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_Profile_WhenUserSent_ReceivesNameAsParameter" result="Pass" time="0.0349319" />
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_Profile_WhenUserSent_ReturnsOneValue" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_Profile_WhenUserSent_ReturnsOneValue" result="Pass" time="0.0101626" />
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_Profile_WhenUserSent_ShowExtendedResults" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_Profile_WhenUserSent_ShowExtendedResults" result="Pass" time="0.0647852" />
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Get_Users_from_List" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Get_Users_from_List" result="Fail" time="0.0594445">
        <failure exception-type="Xunit.Sdk.XunitException">
          <message>Expected string to be \"https://api.twitter.com/1.1/users/lookup.json\", but found &lt;null&gt;.</message>
          <stack-trace>   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 43
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 54
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 32
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 39
   at BoxKite.Twitter.Tests.TestableUserSession.PostAsync(String relativeUrl, SortedDictionary`2 parameters) in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\Helpers\TestableUserSession.cs:line 77
   at BoxKite.Twitter.UsersExtensions.&lt;GetUsersDetailsFull&gt;d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BoxKite.Twitter.Tests.UsersExtensionsTests.&lt;Get_Users_from_List&gt;d__17.MoveNext() in C:\dropbox\oss\nickhodge\BoxKite.Twitter\src\BoxKite.Twitter.Tests\UserAuthModules\UsersExtensionsTests.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()</stack-trace>
        </failure>
      </test>
      <test name="BoxKite.Twitter.Tests.UsersExtensionsTests.Search_Users" type="BoxKite.Twitter.Tests.UsersExtensionsTests" method="Search_Users" result="Pass" time="0.0293726" />
    </class>
    <class name="BoxKite.Twitter.Tests.UserStreamTests" time="2.109" total="17" passed="17" failed="0" skipped="0">
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream1_initial_Tweets" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream1_initial_Tweets" result="Pass" time="0.0387989" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream1_initialFriends" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream1_initialFriends" result="Pass" time="0.05797" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream10_status_mention" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream10_status_mention" result="Pass" time="0.0381855" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream11_statuswithheld" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream11_statuswithheld" result="Pass" time="0.0210836" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream14_event_list_removeuser" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream14_event_list_removeuser" result="Pass" time="0.0680235" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream16_scrubgeo" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream16_scrubgeo" result="Pass" time="0.0191979" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream17_limitnotices" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream17_limitnotices" result="Pass" time="0.0276101" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream18_favorite" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream18_favorite" result="Pass" time="0.0121089" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream19_unfavorite" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream19_unfavorite" result="Pass" time="0.0488129" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream2_mentionofself" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream2_mentionofself" result="Pass" time="0.0795127" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream3_event_follow" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream3_event_follow" result="Pass" time="0.1081881" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream4_event_list_adduser" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream4_event_list_adduser" result="Pass" time="0.0470151" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream5_deleteevent" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream5_deleteevent" result="Pass" time="0.0515726" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream6_dm" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream6_dm" result="Pass" time="0.0206291" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream7_scrubgeo" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream7_scrubgeo" result="Pass" time="0.0248894" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream8_scrubgeo" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream8_scrubgeo" result="Pass" time="0.0306969" />
      <test name="BoxKite.Twitter.Tests.UserStreamTests.UserStream9_statuswithheld" type="BoxKite.Twitter.Tests.UserStreamTests" method="UserStream9_statuswithheld" result="Pass" time="1.4151939" />
    </class>
  </assembly>
</assemblies>